name: GCP read secret
on:
  workflow_dispatch:

jobs:
  get-secret:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          audience: ${{ secrets.GCP_WIF_AUDIENCE }}
          create_credentials_file: true
          export_environment_variables: true

      - id: secrets
        uses: google-github-actions/get-secretmanager-secrets@v3
        with:
          secrets: |
            SECRET: ${{ secrets.GCP_SECRET }}
          export_to_environment: true
          encoding: utf8

      - name: Print secrets (testing)
        run: |
          echo "SECRET length: ${#SECRET}"
          echo "SECRET (first 4 chars only): ${SECRET:0:4}****"
